#!/usr/bin/env python3
"""
logo_to_bitmap.py -- convert a team logo image into a PROGMEM C array
for drawing with Inkplate's drawBitmap(), instead of decoding images
on-device at runtime.

Usage:
    python3 logo_to_bitmap.py seattle.png --mode 1bit --threshold 128 --out seattle_logo.h --name seattle_logo
    python3 logo_to_bitmap.py seattle.png --mode 3color --out seattle_logo.h --name seattle_logo

Modes:
    1bit    -- black/white only, for grayscale Inkplate boards (packs 8
               pixels per byte, MSB first -- matches Adafruit GFX's
               drawBitmap() convention that Inkplate's drawBitmap() also
               follows).
    3color  -- black/white/red, for the Inkplate 2. Produces two packed
               1bpp planes (black plane + red plane) since that's how the
               Inkplate 2's 3-color framebuffer is organized; the header
               includes both arrays plus a small drawTricolorBitmap()
               helper comment showing how to combine them.

Requires: Pillow (`pip install Pillow`)
"""
import argparse
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("This script requires Pillow: pip install Pillow")


def pack_1bit(img, threshold):
    w, h = img.size
    gray = img.convert("L")
    px = gray.load()
    rowbytes = (w + 7) // 8
    data = bytearray(rowbytes * h)
    for y in range(h):
        for x in range(w):
            if px[x, y] < threshold:  # dark pixel -> set bit ("black")
                data[y * rowbytes + (x // 8)] |= 0x80 >> (x % 8)
    return data, rowbytes


def pack_3color(img, threshold, red_saturation_min):
    # Classifies each pixel as white / black / red. Red is detected as
    # "red channel clearly dominant"; tune red_saturation_min if your
    # logo's red doesn't separate cleanly from dark colors.
    w, h = img.size
    rgb = img.convert("RGB")
    px = rgb.load()
    rowbytes = (w + 7) // 8
    black = bytearray(rowbytes * h)
    red = bytearray(rowbytes * h)
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if r > g + red_saturation_min and r > b + red_saturation_min:
                red[y * rowbytes + (x // 8)] |= 0x80 >> (x % 8)
            elif (r + g + b) / 3 < threshold:
                black[y * rowbytes + (x // 8)] |= 0x80 >> (x % 8)
    return black, red, rowbytes


def emit_array(f, name, data):
    f.write(f"const uint8_t {name}[] PROGMEM = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--mode", choices=["1bit", "3color"], default="1bit")
    ap.add_argument("--threshold", type=int, default=128, help="darkness cutoff, 0-255")
    ap.add_argument("--red-saturation-min", type=int, default=40)
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", required=True, help="base name for the generated array(s)")
    ap.add_argument("--max-width", type=int, default=None, help="resize to this width, preserving aspect ratio")
    args = ap.parse_args()

    img = Image.open(args.image)
    if args.max_width and img.width != args.max_width:
        ratio = args.max_width / img.width
        img = img.resize((args.max_width, max(1, int(img.height * ratio))), Image.LANCZOS)

    w, h = img.size

    with open(args.out, "w") as f:
        f.write(f"// Auto-generated by tools/logo_to_bitmap.py from {args.image}. Do not edit by hand.\n")
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write(f"constexpr int {args.name}_w = {w};\n")
        f.write(f"constexpr int {args.name}_h = {h};\n\n")

        if args.mode == "1bit":
            data, _ = pack_1bit(img, args.threshold)
            emit_array(f, f"{args.name}_bits", data)
            f.write(
                f"\n// Usage: display.drawBitmap(x, y, {args.name}_bits, {args.name}_w, {args.name}_h, BLACK);\n"
                f"// (BLACK/WHITE come from the Inkplate library itself -- valid on every\n"
                f"// grayscale board; the Inkplate 2 uses INKPLATE2_BLACK/WHITE/RED instead,\n"
                f"// see the 3color usage comment below.)\n"
            )
        else:
            black, red, _ = pack_3color(img, args.threshold, args.red_saturation_min)
            emit_array(f, f"{args.name}_black_bits", black)
            f.write("\n")
            emit_array(f, f"{args.name}_red_bits", red)
            f.write(
                f"\n// Usage: draw the black plane with INKPLATE2_BLACK, then the red plane\n"
                f"// with INKPLATE2_RED, both via display.drawBitmap(x, y, ..., {args.name}_w, {args.name}_h, color).\n"
            )

    print(f"Wrote {args.out} ({w}x{h}, mode={args.mode})")


if __name__ == "__main__":
    main()
